
set -sg escape-time 10
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g renumber-windows on
set -g extended-keys on
set -g extended-keys-format csi-u

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'onedark'
set -g @tmux2k-left-plugins false
set -g @tmux2k-right-plugins false
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'

# new panes and windows are open in pwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# initialize TMUX plugin manager 
# (keep this line at the very bottom of tmux.conf)
# prefix + I (capital i, as in Install) to fetch the plugin.
run '~/.tmux/plugins/tpm/tpm'
